name: "Comprueba presencia de ficheros"
on: [pull_request, push]

jobs:
  file_presence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Ficheros inamovibles"
        uses: JJ/files-present-action@releases/v1
        with:
          files: "hitos.json"
